services:
  comments-app:
    build:
      context: .
      args:
        - env=development
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: password
    depends_on:
      - postgres-db
      - redis
      - rabbitmq
    networks:
      - comments-app-network
    container_name: comments_app
    restart: on-failure

  postgres-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - comments-app-network
    container_name: postgres-db
    restart: on-failure

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    networks:
      - comments-app-network
    container_name: redis
    restart: on-failure

  rabbitmq:
    image: rabbitmq:4.0.3-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: vhost
    expose:
      - "5672"
    networks:
      - comments-app-network
    container_name: rabbitmq
    restart: on-failure

networks:
  comments-app-network:
    driver: bridge

volumes:
  postgres_data:
